InternetShop/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('basket/', include('basket.urls', namespace='baskets')),

    # path('', include('social_django.urls', namespace='social')),
    path("", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path("__debug__/", include("debug_toolbar.urls")),

basket/urls.py
from django.urls import path
from basket.views import basket_add, basket_remove

app_name = "basket"

urlpatterns = [
    path('basket-add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket-remove/<int:id>/', basket_remove, name='basket_remove')
]

users/urls.py
from django.urls import path
from users.views import  logout, verify, UserRegistrationForm, UserProfileForm, UserLoginForm

app_name = "users"

urlpatterns = [
    path('', UserLoginForm.as_view(), name='user'), #login
    path('register/', UserRegistrationForm.as_view(), name='register'),
    path('logout/', logout, name='logout'),
    path('profile/<int:pk>/', UserProfileForm.as_view(), name='profile'),


    path('verify/<str:email>/<str:activate_key>', verify, name='verification'),


]

basket/models.py
from django.db import models
from users.models import User
from products.models import Product

# Create your models here.
class Basket(models.Model):
    User = models.ForeignKey(User, on_delete=models.CASCADE)
    Product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Корзина для {self.User.username}| Продукт {self.Product.name}"

    def sum(self):
        return self.quantity * self.Product.price

    def total_sum(self):
        baskets = Basket.objects.filter(User=self.User)
        total = 0
        for basket in baskets:
            total += basket.sum()
        return total

    def total_quantity(self):
        total = 0
        baskets = Basket.objects.filter(User=self.User)
        for basket in baskets:
            total += basket.quantity
        return total


    # def total_sum(request):
    #     baskets = Basket.objects.filter(user=request.user)
    #     total = 0
    #     for basket in baskets:
    #         total += basket.sum()
    #         return total
    #

basket/views.py
from django.shortcuts import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from products.models import Product
from basket.models import Basket


# Create your views here
@login_required
def basket_add(request, product_id):
    user = request.user
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(User=user, Product=product)
    if not baskets:
        Basket.objects.create(User=user, Product=product, quantity=1)
        return HttpResponseRedirect(request.META['HTTP_REFERER'])
    else:
        basket = baskets.first()
        basket.quantity +=1
        basket.save()
        messages.success("Товар добавлен в корзину!")
        return HttpResponseRedirect(request.META['HTTP_REFERER'])



@login_required
def basket_remove(request, id):
    basket = Basket.objects.get(id=id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])

basket/templates/basket/basket.html
{% load static %}


{% if baskets %}
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина <span class="badge badge-secondary badge-pill">{{ baskets.0.total_quantity }}</span>
    </h4>
    {% for basket in baskets %}
{#        {% if  form.errors %}#}
{#        <div class="alert alert-warning alert-dismissible fade show" role="alert"#}
{#             style="margin-top: 50px;">#}
{#        {{ form.errors}}#}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ basket.Product.name }}</h5>
                <p class="card-text">{{ basket.Product.desc }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-light">
                    <div class="row text-center">
                        <div class="col-lg-4">
                            <input name="basketID" type="number" class="form-control"
                                   value="{{ basket.quantity }}" min="0">
                        </div>
                        <div class="col-lg-4">{{ basket.sum }} руб </div>
                        <div class="col-lg-4">
                            <a href="{% url "baskets:basket_remove" basket.id %}">
                                <i class="fas fa-trash">Удалить Корзину</i>
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    {% endfor %}
    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{baskets.0.total_sum}}</h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right" href="../orders/checkout_order.html">
        Оформить заказ
    </a>
{% else %}
    <h4 class="mt-3 mb-3 text-center">
        Корзина пуста
    </h4>
{% endif %}