InternetShop/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('basket/', include('basket.urls', namespace='baskets')),

    # path('', include('social_django.urls', namespace='social')),
    path("", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path("__debug__/", include("debug_toolbar.urls")),

users/urls.py
from django.urls import path
from users.views import  logout, verify, UserRegistrationForm, UserProfileForm, UserLoginForm

app_name = "users"

urlpatterns = [
    path('', UserLoginForm.as_view(), name='user'), #login
    path('register/', UserRegistrationForm.as_view(), name='register'),
    path('logout/', logout, name='logout'),
    path('profile/<int:pk>/', UserProfileForm.as_view(), name='profile'),


    path('verify/<str:email>/<str:activate_key>', verify, name='verification'),


]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.dispatch import receiver
from django.utils.timezone import now
from datetime import timedelta
from django.db.models.signals import post_save


# Create your models here.
class User(AbstractUser):
    image = models.ImageField(upload_to='users_image', blank=True, null=True)
    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(default=(now() + timedelta(hours=48)), blank=True, null=True)

    def safe_delete(self):
        self.is_active = False
        self.save()

    @property
    def is_activation_key_expired(self):
        try:
            if now() <= self.activation_key_expires:
                return False
        except Exception as e:
            pass
        return True


class UserProfile(models.Model):
    MALE = 'M'
    FEMALE = 'F'

    Genders = (
        (MALE, 'Мужчина'),
        (FEMALE, 'Женщина')
    )

    user = models.OneToOneField(User, null=False, db_index=True, on_delete=models.CASCADE)
    about = models.TextField(verbose_name='О себе', blank=True, null=True)
    gender = models.CharField(verbose_name='пол', choices=Genders, blank=True, max_length=1)


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.userprofile.save()

users/forms.py
import hashlib
from random import random

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from django import forms
from users.models import User, UserProfile


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput
        (attrs={'class': 'form-control py-4', "placeholder": "Введите имя пользователя"}))
    password = forms.CharField(widget=forms.PasswordInput
        (attrs={'class': 'form-control py-4', "placeholder": "Введите  пароль"}))

    class Meta:
        model = User
        fields = ("username", "password")


class UserRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput
        (attrs={'class': 'form-control py-4', "placeholder": "Введите имя пользователя"}))
    first_name = forms.CharField(widget=forms.TextInput
        (attrs={'class': 'form-control py-4', "placeholder": "Введите имя"}))
    last_name = forms.CharField(widget=forms.TextInput
        (attrs={"class": 'form-control py-4', "placeholder": "Введите фамилию"}))
    email = forms.CharField(widget=forms.EmailInput
        (attrs={'class': 'form-control py-4', "placegolder": "Введите адрес эл. почты"}))
    password1 = forms.CharField(widget=forms.PasswordInput
        (attrs={'class': 'form-control py-4', "placeholder": "Введите  пароль"}))
    password2 = forms.CharField(widget=forms.PasswordInput
        (attrs={'class': 'form-control py-4', "placeholder": "Введите  пароль"}))

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save()
        user.is_active = False
        salt = hashlib.sha1(str(random()).encode('utf-8')).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode('utf-8')).hexdigest()
        user.save(update_fields=['is_active', 'activation_key'])
        return user


class UserProfileForm(UserChangeForm):
    username = forms.CharField(widget=forms.TextInput
    (attrs={'class': 'form-control py-4', "placeholder": "Введите имя пользователя", "readonly": True}), )
    first_name = forms.CharField(widget=forms.TextInput
    (attrs={'class': 'form-control py-4', "placeholder": "Введите имя"}))
    last_name = forms.CharField(widget=forms.TextInput
    (attrs={"class": 'form-control py-4', "placeholder": "Введите фамилию"}))
    email = forms.CharField(widget=forms.EmailInput
    (attrs={'class': 'form-control py-4', "placegolder": "Введите адрес эл. почты", "readonly": True}))
    image = forms.ImageField(widget=forms.FileInput
    (attrs={'class': 'custom-file-input'}), required=False)

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name", "email", "image")

class UserProfileEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('about', 'gender')

users/views.py
from django.contrib.auth.views import LoginView
from django.core.mail import send_mail
from django.conf import settings
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import CreateView, UpdateView

from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from users.models import User, UserProfile
from django.urls import reverse, reverse_lazy
from django.contrib import auth, messages


# Classes


# Adding title context
class TitleMixin:
    title = None

    def get_context_data(self, **kwargs):
        context = super(TitleMixin, self).get_context_data(**kwargs)
        context['title'] = self.title
        context['form'] = self.form_class()
        return context


# Class for user login
class UserLoginForm(TitleMixin, LoginView):
    redirect_authenticated_user = True
    template_name = 'users/login.html'
    form_class = UserLoginForm
    title = 'Авторизация пользователя'

    def form_invalid(self, form):
        messages.error(self.request, 'Invalid username or password')
        return self.render_to_response(self.get_context_data(form=form))


# Class for user Creation
class UserRegistrationForm(TitleMixin, CreateView):
    title = 'Регистрация пользователя'
    model = User
    form_class = UserRegistrationForm
    template_name = 'users/register.html'
    success_url = reverse_lazy("users:user")
    success_message = 'Пользователь успешно создан'

    def send_verify_link(self, user):
        verify_link = reverse('users:verification', args=[user.email, user.activation_key])
        subject = 'АКТИВАЦИЯ ПОЛЬЗОВАТЕЛЯ'
        message = f'Активируйте пользователя {user.username} пройдя по ссылке {settings.DOMAIN_NAME}{verify_link}'
        return send_mail(subject, message, settings.EMAIL_HOST_USER, fail_silently=False, recipient_list=[user.email])

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)

        if form.is_valid():
            user = form.save()
            self.send_verify_link(user)
            return HttpResponseRedirect(reverse('users:user'))
        else:
            return super().get(request, *args, **kwargs)


# Class to generate user profile information, will be reworked
# class UserProfileForm(TitleMixin, UpdateView):
#     model = User
#     form_class = UserProfileForm
#     title = 'Профиль пользователя'
#     template_name = 'users/profile.html'


class UserProfileForm(TitleMixin, UpdateView):
    model = User
    edit_form = UserProfileForm
    profile_form = UserProfile
    title = 'Профиль пользователя'
    template_name = 'users/profile.html'


# Functions


# Logout function, no need to CBV
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("index"))


# Function for user verification from email
def verify(request, email, activate_key):
    try:
        user = User.objects.get(email=email)
        if user and user.activation_key == activate_key and not user.is_activation_key_expired:
            user.activation_key = ''
            user.activation_key_expires = None
            user.is_active = True
            user.save(update_fields=['activation_key', 'activation_key_expires', 'is_active'])
            auth.login(request, user)
            return render(request, 'users/verification.html')
    except Exception as e:
        pass
    else:
        return render(request, 'users/verification.html')

users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>GeekShop - Регистрация</title>
    <link href="{% static "/vendor/css/auth-admin.css" %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static "/vendor/js/auth-admin.js" %}"></script>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load socialaccount %}
{% load static %}

{% block content %}
    <div class="col-lg-5">
        {% if messages or form.errors %}
        <div class="alert alert-dismissible fade show
        {% if messages %}alert-success {% else %} alert-warning{% endif %}" role="alert"
             style="margin-top: 50px;">
            {% if messages %}
                {%  for message in messages %}
                    {{ message }}
                {% endfor %}
            {%  else %}
                {{  form.non_field_errors }}
            {% endif %}
        </div>
        {% endif %}
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header">
                <h3 class="text-center font-weight-light my-4">Авторизация</h3>
            </div>
            <div class="card-body">
                <form method="post" action="{% url 'users:user' %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{form.username}}
                    </div>
                    <div class="form-group">
                        <label class="small mb-1" for="{{ form.password.id_for_label }}">Пароль</label>
                        {{ form.password }}
                    </div>

                    <div
                            class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                        <a class="small" href="#">Забыли пароль?</a>
                        <input class="btn btn-primary" type="submit" value="Авторизоваться">
                    </div>
                    <div
                            class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                        <a href="{% provider_login_url 'google'%}">

                            <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                        </a>
                        <a href="#">
{#                            {% url 'social:begin' 'vk_oauth2' %}#}
                            <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                        </a>
                        <a href="#">
                            <i class="fab fa-facebook fa-2x" style="color: #405794;"></i>
                        </a>
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small"><a href="{% url "users:register" %}">Нужен аккаунт? Зарегистрируйся!</a></div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'products/base.html' %}
{% load static %}


{% block css %}
    <link href="{%  static "/vendor/css/profile.css"%}" rel="stylesheet">
{% endblock %}


{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <h4 class="mt-3 mb-3">Профиль</h4>
                <div class="col-lg-12 text-center">
                    <img width="100" height="100"
                         src="{% if user.image %} {{user.image.url}}{% else %}{%  static "vendor/img/users/default_avatar.jpg" %} {% endif %}"
                         class="img-thumbnail">
                </div>
                <form action="{% url "users:profile" object.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_label }}">Выберите изображение</label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email}}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-5">
                {% include "basket/basket.html" %}
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
    <div class="col-lg-7">
        {% if  form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert"
             style="margin-top: 50px;">
        {{ form.errors}}
        </div>
        {% endif %}
        <div class="card shadow-lg border-0 rounded-lg mt-5">
            <div class="card-header"><h3 class="text-center font-weight-light my-4 ">Создать аккаунт</h3>
            </div>
            <div class="card-body">
                <form method="post" action="{% url 'users:register' %}">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{  form.first_name.id_for_label }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-6">
                            <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-md-6">
                            <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                                почты</label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password1.id_for_label }}">Пароль</label>
                                {{ form.password1 }}
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.password2.id_for_label }}">Подтверждение
                                    пароля</label>
                                {{ form.password2 }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group mt-4 mb-0">
                        <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                    </div>
                </form>
            </div>
            <div class="card-footer text-center">
                <div class="small"><a href="{% url 'users:user' %}">Уже есть аккаунт? Авторизоваться</a></div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/verification.html
{% extends 'users/base.html' %}
{% load static %}

{% block content %}
    {% if user %}\
        <h3>Поздравляем! Вы прошли верификацию! Пользователь {{ user.username }}</h3>
    {% else %}
        <h3> Верификация не пройдена </h3>
    {% endif %}
{% endblock %}