InternetShop/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admins/', include('admins.urls', namespace='admins')),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),
    path('users/', include('users.urls', namespace='users')),
    path('basket/', include('basket.urls', namespace='baskets')),

    # path('', include('social_django.urls', namespace='social')),
    path("", include("allauth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += path("__debug__/", include("debug_toolbar.urls")),

basket/urls.py
from django.urls import path
from basket.views import basket_add, basket_remove

app_name = "basket"

urlpatterns = [
    path('basket-add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket-remove/<int:id>/', basket_remove, name='basket_remove')
]

products/urls.py
from django.urls import path
from products.views import products

app_name = "products"

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:category_id>', products, name='category'),
    path('page/<int:page>', products, name='page')
]

users/urls.py
from django.urls import path
from users.views import  logout, verify, UserRegistrationForm, UserProfileForm, UserLoginForm

app_name = "users"

urlpatterns = [
    path('', UserLoginForm.as_view(), name='user'), #login
    path('register/', UserRegistrationForm.as_view(), name='register'),
    path('logout/', logout, name='logout'),
    path('profile/<int:pk>/', UserProfileForm.as_view(), name='profile'),


    path('verify/<str:email>/<str:activate_key>', verify, name='verification'),


]

products/models.py
from django.db import models

# Create your models here.


class ProductCategory(models.Model):
    name = models.CharField(max_length=50, unique=True)
    desc = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.name}'


class Product(models.Model):
    name = models.CharField(max_length=200, unique=True)
    image = models.ImageField(upload_to='products_image', blank=True, null=True)
    desc = models.TextField()
    quantity = models.PositiveIntegerField(default=0)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}'

products/views.py
from django.shortcuts import render
from products.models import Product, ProductCategory
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.

def index(request):
    context = {
        'title': "GeekShop"
    }
    return render(request, 'products/index.html', context)


def products(request, category_id=None, page=1):
    if category_id:
        products = Product.objects.filter(category_id=category_id)
    else:
        products = Product.objects.all()

    paginator = Paginator(products, 2)
    try:
        products_paginator = paginator.page(page)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)

    context = {
        'title': "GeekShop - Продукты",
        'products': products_paginator,
        'categories': ProductCategory.objects.all()
    }
    return render(request, 'products/products.html', context)

products/templates/products/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %}
    {% endblock %}

</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{%  url "users:profile" user.id %}">Профиль</a>
                            </li>
                            <li><a class="dropdown-item" href="orders/orders.html">Заказы</a></li>
                            {% if user.is_staff or user.is_superuser %}
                                 <li><a class="dropdown-item" href="{% url "admins:index" %}">Админ-панель</a></li>
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url "users:logout" %}">
                                    Выйти
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:user' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}

{% block footer %}{% endblock %}


<!-- Bootstrap core JavaScript -->
<script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static "vendor/fontawesome/fontawesome-icons.js" %} crossorigin=" anonymous
" %}"></script>

</body>

</html>

products/templates/products/index.html
{% extends "products/base.html"%}
{% load static %}

{% block css %}
    <!-- Custom styles for this template -->
    <link href="{% static "vendor/css/index.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">GeekShop Store</h1>
                <p>
                    Новые образы и лучшие бренды на GeekShop Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" href="{% url 'products:index' %}">
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
</section>
{% endblock %}

products/templates/products/products.html
{% extends 'products/base.html' %}
{% load static %}



{% block css %}
    <!-- Custom styles for this template -->
    <link href="{% static "vendor/css/products.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    {% for category in categories %}
                        <a href="{% url 'products:category' category.id %}"  class="list-group-item">
                            {{ category.name }}
                        </a>
                    {% endfor %}


{#                    {% for category in categories %}#}
{#                        <a href="{% url "products:category" category_id %}"#}
{#                           class="list-group-item">{{ category.name }}</a>#}
{#                    {% endfor %}#}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid"
                                 src="{% static "vendor/img/slides/slide-1.jpg" %}" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid"
                                 src="{% static "vendor/img/slides/slide-2.jpg" %}" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid"
                                 src="{% static "vendor/img/slides/slide-3.jpg" %}" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">
                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top"
                                         src="{{ product.image.url }}"
                                         alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="#">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price }}</h5>
                                    <p class="card-text">{{ product.desc }}</p>
                                </div>
                                <div class="card-footer text-center">
                                    <a href="{% url 'baskets:basket_add' product.id %}" class="btn btn-outline-success">
                                        Отправить в корзину
                                    </a>
                                </div>
                            </div>
                        </div>

                    {% endfor %}
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-center">
                            <li class="page-item {% if not products.has_previous %}disabled {% endif %}">
                                <a class="page-link"
                                   href="

                                           {% if products.has_previous %}{% url "products:page" products.previous_page_number %}{% else %}#{% endif %}"
                                   tabindex="-1" aria-disabled="true">
                                    Previous
                                </a>
                            </li>
                            {% for page in products.paginator.page_range %}
                                <li class="page-item"><a class="page-link" href="{% url "products:page" page %}">
                                    {{ page }}
                                </a></li>
                            {% endfor %}
                            <li class="page-item {% if not products.has_next %}disabled {% endif %}">
                                <a class="page-link" href="

                                        {% if products.has_next %}{% url "products:page" products.next_page_number %}{% else %}#{% endif %}"
                                >
                                    Next
                                </a>
                            </li>
                        </ul>
                    </nav>

                </div>

            </div>
        </div>

    </div>

{% endblock %}


{% block footer %}
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}